version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
#      - mvn test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package -Dmaven.test.skip=true
artifacts:
  files:
    - target/pizza-0.0.1-SNAPSHOT.jar
